apiVersion: v1
kind: Pod
metadata:
  name: cnet-cpu3
spec:
  containers:
  - name: cnet-cpu3
    image: hurunyan/cuda10
    args: ["sleep", "infinity"]
    resources:
      limits:
        memory: "8Gi"
        cpu: 2
      requests:
        memory: "8Gi"
        cpu: 2
    volumeMounts:
      - mountPath: /ceph
        name: sceneflow-datasets
  volumes:
  - name: sceneflow-datasets
    persistentVolumeClaim:
      claimName: sceneflow-datasets

