apiVersion: batch/v1
kind: Job
metadata:
  name: cycle-gan-gta-cs
spec:
  template:
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: gpu-type
               operator: In
               values: 
                 - 1080Ti
                 - 2080Ti
      containers:
      - name: cycle-gan-gta-cs
        image: pytorch/pytorch:0.4.1-cuda9-cudnn7-devel
        command:
        - sh
        - -c
        - "cp -r /ceph/cycada/cyclegan_data /mnt/data/ && mv /mnt/data/cyclegan_data/trainA /mnt/data/cyclegan_data/testA && mv /mnt/data/cyclegan_data/trainB /mnt/data/cyclegan_data/testB && apt update && apt install -y python3-pip tmux vim curl git unzip ffmpeg libsm6 libxext6 && python3 -m pip install --upgrade pip && cd /opt/repo/cycada_release/cyclegan && pip install -r requirements.txt && chmod u+x test_gta2cityscapes.sh && ./test_gta2cityscapes.sh && cp -r /mnt/data/cyclegan_data/adapted /ceph/gta_adapted"
        volumeMounts:
        - name: data
          mountPath: /mnt/data
        - name: git-repo
          mountPath: /opt/repo
        - name: sceneflow-datasets
          mountPath: /ceph
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            memory: 3Gi
            cpu: "1"
            nvidia.com/gpu: "1"
            ephemeral-storage: 100Gi
          requests:
            memory: 2Gi
            cpu: "1"
            nvidia.com/gpu: "1"
            ephemeral-storage: 100Gi
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone 
          - --recursive
          - https://github.com/raviteja-kvns/cycada_release.git
          - /opt/repo/cycada_release
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: data
        emptyDir: {}
      - name: git-repo
        emptyDir: {}
      - name: sceneflow-datasets
        persistentVolumeClaim:
          claimName: sceneflow-datasets
      - name: dshm
        emptyDir:
          medium: Memory
      restartPolicy: "Never"
  backoffLimit: 5
