apiVersion: batch/v1
kind: Job
metadata:
  name: dlow-gta-cs
spec:
  template:
    spec:
      nodeSelector:
       kubernetes.io/hostname: k8s-ravi-01.calit2.optiputer.net
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: gpu-type
               operator: In
               values: 
                 - titan-xp 
      containers:
      - name: dlow-gta-cs
        image: floydhub/pytorch:0.3.1-gpu.cuda9cudnn7-py3.30
        command:
        - sh
        - -c
        - "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157 && curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add - && apt update && apt install -y python3-pip tmux vim curl git unzip ffmpeg libsm6 libxext6 && cp -r /ceph/cycada/cyclegan_data /mnt/data/ && python3 -m pip install --upgrade pip && cd /opt/repo/DLOW && pip install -r requirements.txt && CUDA_LAUNCH_BLOCKING=1 python train.py --dataroot /mnt/data/cyclegan_data/ --name dlow_gta2cityscapes --model cycle_gan --checkpoints_dir /ceph/dlow_checkpoints --lambda_identity 1.0 --progressive_epoch 10 --lambda_A 10.0 --lambda_B 10.0 --lambda_GA_classification 1.0 --lambda_GB_classification 1.0 --lambda_GA_classification_0 1.0 --lambda_GB_classification_0 1.0 --lambda_GA 1.0 --lambda_GB 1.0 --resize_or_crop scale_width_and_crop --loadSize 1024 --fineSize 400 --save_epoch_freq 1 --display_id 0 --gpu_ids=0 --continue_train"
        volumeMounts:
        - name: data
          mountPath: /mnt/data
        - name: git-repo
          mountPath: /opt/repo
        - name: sceneflow-datasets
          mountPath: /ceph
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            memory: 5Gi
            cpu: "2"
            nvidia.com/gpu: "1"
            ephemeral-storage: 200Gi
          requests:
            memory: 4Gi 
            cpu: "1"
            nvidia.com/gpu: "1"
            ephemeral-storage: 200Gi
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone 
          - https://github.com/shreyas23/DLOW.git
          - /opt/repo/DLOW
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: data
        emptyDir: {}
      - name: git-repo
        emptyDir: {}
      - name: sceneflow-datasets
        persistentVolumeClaim:
          claimName: sceneflow-datasets
      - name: dshm
        emptyDir:
          medium: Memory
      restartPolicy: "Never"
  backoffLimit: 1
