apiVersion: v1
kind: Pod
metadata:
  name: cnet-cpu
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In 
            values:
            - 1080Ti
  containers:
  - name: cnet-cpu
    image: hurunyan/cuda10
    args: ["sleep", "infinity"]
    resources:
      limits:
        memory: "8Gi"
        cpu: 2
        nvidia.com/gpu: 1
        ephemeral-storage: 100Gi
      requests:
        memory: "8Gi"
        cpu: 2
        nvidia.com/gpu: 1
        ephemeral-storage: 100Gi
    volumeMounts:
      - mountPath: /ceph
        name: sceneflow-datasets
      - mountPath: /mnt/data/
        name: data
  volumes:
  - name: sceneflow-datasets
    persistentVolumeClaim:
      claimName: sceneflow-datasets
  - name: data
    emptyDir: {}
