apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In 
            values:
            - 1080Ti
  containers:
  - name: gpu-pod
    image: pytorch/pytorch:0.4.1-cuda9-cudnn7-devel
    args: ["sleep", "infinity"]
    resources:
      limits:
        memory: "8Gi"
        cpu: 2
        nvidia.com/gpu: 1
        ephemeral-storage: 100Gi
      requests:
        memory: "8Gi"
        cpu: 2
        nvidia.com/gpu: 1
        ephemeral-storage: 100Gi
    volumeMounts:
      - mountPath: /ceph
        name: sceneflow-datasets
      - mountPath: /mnt/data/
        name: data
      - name: dshm
        mountPath: /dev/shm
  volumes:
  - name: sceneflow-datasets
    persistentVolumeClaim:
      claimName: sceneflow-datasets
  - name: data
    emptyDir: {}
  - name: dshm
    emptyDir:
      medium: Memory
